export const NAVIGATE = "@@JARL_REACT/NAVIGATE";
export const NAVIGATE_START = "@@JARL_REACT/NAVIGATE_START";
export const NAVIGATE_ERROR = "@@JARL_REACT/NAVIGATE_ERROR";
export const NAVIGATE_END = "@@JARL_REACT/NAVIGATE_END";
export const NAVIGATE_TRANSITION_BEGIN =
    "@@JARL_REACT/NAVIGATE_TRANSITION_BEGIN";
export const NAVIGATE_TRANSITION_IN = "@@JARL_REACT/NAVIGATE_TRANSITION_IN";
export const NAVIGATE_TRANSITION_COMPLETE =
    "@@JARL_REACT/NAVIGATE_TRANSITION_COMPLETE";
