export const NAVIGATE = "NAVIGATE";
export const NAVIGATE_START = "NAVIGATE_START";
export const NAVIGATE_ERROR = "NAVIGATE_ERROR";
export const NAVIGATE_END = "NAVIGATE_END";
export const NAVIGATE_TRANSITION_IN = "NAVIGATE_TRANSITION_IN";
export const NAVIGATE_TRANSITION_COMPLETE = "NAVIGATE_TRANSITION_COMPLETE";
